project_id = "ofbypucaiibkpnfwzrlo"

[functions]
[functions.fetch-binance-whales]
verify_jwt = true

[functions.fetch-binance-spot]
verify_jwt = true

[functions.fetch-binance-margin]
verify_jwt = true

[functions.fetch-binance-pairs]
verify_jwt = true

[functions.fetch-ip]
verify_jwt = false